In [91]:
import pandas as pd
import numpy as np

In [92]:
df = pd.read_csv('../dataset/processed/cleaned_house_prices.csv')
df.head()

,TYPE,PRICE,BEDS,BATH,PROPERTYSQFT,ADDRESS,STATE,LOCALITY,FORMATTED_ADDRESS
0,House for sale,94601238.0,5,5,5938.49,"Moratuwa, Colombo",Colombo,Moratuwa,"Moratuwa, Colombo"
1,House for sale,46044725.0,3,3,1768.45,"Homagama, Colombo",Colombo,Homagama,"Homagama, Colombo"
2,House for sale,90985626.0,5,4,5063.38,"Boralesgamuwa, Colombo",Colombo,Boralesgamuwa,"Boralesgamuwa, Colombo"
3,House for sale,28967644.0,3,2,2619.82,"Piliyandala, Colombo",Colombo,Piliyandala,"Piliyandala, Colombo"
4,Villa for sale,98596073.0,5,5,4914.25,"Boralesgamuwa, Colombo",Colombo,Boralesgamuwa,"Boralesgamuwa, Colombo"

In [93]:
target = "PRICE"

In [94]:
columns_to_drop = [
    "STREET_NAME",
    "BROKERTITLE",
    "MAIN_ADDRESS",
    "FORMATTED_ADDRESS",
    "ADMINISTRATIVE_AREA_LEVEL_2"
]

df_fe = df.drop(
    columns=columns_to_drop,
    errors="ignore"
)

print(df_fe.columns)

Index(['TYPE', 'PRICE', 'BEDS', 'BATH', 'PROPERTYSQFT', 'ADDRESS', 'STATE',
       'LOCALITY'],
      dtype='object')

In [95]:
df_fe.isnull().sum()

TYPE            0
PRICE           0
BEDS            0
BATH            0
PROPERTYSQFT    0
ADDRESS         0
STATE           0
LOCALITY        0
dtype: int64

In [96]:
categorical_features = [
    "TYPE",
    "LOCALITY",
    "ADDRESS",
    "STATE"
]

numerical_features = [
    "PRICE",
    "PROPERTYSQFT",
    "BEDS",
    "BATH"
]

In [97]:
# price per square foot
df_fe["PRICE_PER_SQFT"] = df_fe["PRICE"] / df_fe["PROPERTYSQFT"]

In [98]:
# value category

def size_category(sqft):

    if sqft < 1000:
        return "Small"

    elif sqft < 2000:
        return "Medium"

    elif sqft < 3500:
        return "Large"

    else:
        return "Very Large"


df_fe["SIZE_CATEGORY"] = (
    df_fe["PROPERTYSQFT"]
    .apply(size_category)
)

In [99]:
df_fe["SIZE_CATEGORY"].value_counts()

SIZE_CATEGORY
Very Large    1224
Large         1013
Medium         626
Small          134
Name: count, dtype: int64

In [100]:
df_fe.head()

,TYPE,PRICE,BEDS,BATH,PROPERTYSQFT,ADDRESS,STATE,LOCALITY,PRICE_PER_SQFT,SIZE_CATEGORY
0,House for sale,94601238.0,5,5,5938.49,"Moratuwa, Colombo",Colombo,Moratuwa,15930.183936,Very Large
1,House for sale,46044725.0,3,3,1768.45,"Homagama, Colombo",Colombo,Homagama,26036.769487,Medium
2,House for sale,90985626.0,5,4,5063.38,"Boralesgamuwa, Colombo",Colombo,Boralesgamuwa,17969.345773,Very Large
3,House for sale,28967644.0,3,2,2619.82,"Piliyandala, Colombo",Colombo,Piliyandala,11057.112321,Large
4,Villa for sale,98596073.0,5,5,4914.25,"Boralesgamuwa, Colombo",Colombo,Boralesgamuwa,20063.300198,Very Large

In [101]:
# beads per bath ratio

df_fe["BEDS_PER_BATH"] = df_fe["BEDS"] / df_fe["BATH"].replace(0, np.nan)

df_fe["BEDS_PER_BATH"] = (
    df_fe["BEDS_PER_BATH"]
    .fillna(0)
)

In [102]:
df_fe.head()

,TYPE,PRICE,BEDS,BATH,PROPERTYSQFT,ADDRESS,STATE,LOCALITY,PRICE_PER_SQFT,SIZE_CATEGORY,BEDS_PER_BATH
0,House for sale,94601238.0,5,5,5938.49,"Moratuwa, Colombo",Colombo,Moratuwa,15930.183936,Very Large,1.00
1,House for sale,46044725.0,3,3,1768.45,"Homagama, Colombo",Colombo,Homagama,26036.769487,Medium,1.00
2,House for sale,90985626.0,5,4,5063.38,"Boralesgamuwa, Colombo",Colombo,Boralesgamuwa,17969.345773,Very Large,1.25
3,House for sale,28967644.0,3,2,2619.82,"Piliyandala, Colombo",Colombo,Piliyandala,11057.112321,Large,1.50
4,Villa for sale,98596073.0,5,5,4914.25,"Boralesgamuwa, Colombo",Colombo,Boralesgamuwa,20063.300198,Very Large,1.00

In [103]:
# total room related feature

df_fe["TOTAL_BEDS_BATH"] = (
    df_fe["BEDS"] + df_fe["BATH"]
)

In [104]:
df_fe.head()

,TYPE,PRICE,BEDS,BATH,PROPERTYSQFT,ADDRESS,STATE,LOCALITY,PRICE_PER_SQFT,SIZE_CATEGORY,BEDS_PER_BATH,TOTAL_BEDS_BATH
0,House for sale,94601238.0,5,5,5938.49,"Moratuwa, Colombo",Colombo,Moratuwa,15930.183936,Very Large,1.00,10
1,House for sale,46044725.0,3,3,1768.45,"Homagama, Colombo",Colombo,Homagama,26036.769487,Medium,1.00,6
2,House for sale,90985626.0,5,4,5063.38,"Boralesgamuwa, Colombo",Colombo,Boralesgamuwa,17969.345773,Very Large,1.25,9
3,House for sale,28967644.0,3,2,2619.82,"Piliyandala, Colombo",Colombo,Piliyandala,11057.112321,Large,1.50,5
4,Villa for sale,98596073.0,5,5,4914.25,"Boralesgamuwa, Colombo",Colombo,Boralesgamuwa,20063.300198,Very Large,1.00,10

In [105]:
df_fe.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2997 entries, 0 to 2996
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   TYPE             2997 non-null   object
 1   PRICE            2997 non-null   float64
 2   BEDS             2997 non-null   int64
 3   BATH             2997 non-null   int64
 4   PROPERTYSQFT     2997 non-null   float64
 5   ADDRESS          2997 non-null   object
 6   STATE            2997 non-null   object
 7   LOCALITY         2997 non-null   object
 8   PRICE_PER_SQFT   2997 non-null   float64
 9   SIZE_CATEGORY    2997 non-null   object
 10  BEDS_PER_BATH    2997 non-null   float64
 11  TOTAL_BEDS_BATH  2997 non-null   int64
dtypes: float64(4), int64(3), object(5)
memory usage: 281.1+ KB

In [106]:
df_fe.describe()

,PRICE,BEDS,BATH,PROPERTYSQFT,PRICE_PER_SQFT,BEDS_PER_BATH,TOTAL_BEDS_BATH
count,2.997000e+03,2997.000000,2997.000000,2997.000000,2997.000000,2997.000000,2997.000000
mean,8.620929e+07,4.244912,3.621622,3307.545506,23758.307864,1.221317,7.866533
std,8.551143e+07,1.663661,1.400567,1828.523152,12636.675519,0.355094,2.919172
min,5.500000e+06,1.000000,1.000000,500.000000,1375.000000,0.333333,2.000000
25%,3.323737e+07,3.000000,3.000000,1974.950000,14048.105295,1.000000,6.000000
50%,5.821799e+07,4.000000,3.000000,3083.410000,20297.878148,1.166667,8.000000
75%,1.078407e+08,5.000000,4.000000,4139.820000,32410.593618,1.400000,9.000000
max,8.500000e+08,10.000000,10.000000,15000.000000,130769.230769,3.000000,20.000000

In [107]:
features = [
    "BEDS",
    "BATH",
    "PROPERTYSQFT",
    "TYPE",
    "STATE",
    "LOCALITY"
]

X = df_fe[features]
y = df_fe[target]

print("X shape:", X.shape)
print("y shape:", y.shape)

X shape: (2997, 6)
y shape: (2997,)

## Train/ test split data

In [108]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [109]:
print(X_train.shape)
print(X_test.shape)

(2397, 6)
(600, 6)

## Preprocessing pipeline

In [110]:
df_fe.head()

,TYPE,PRICE,BEDS,BATH,PROPERTYSQFT,ADDRESS,STATE,LOCALITY,PRICE_PER_SQFT,SIZE_CATEGORY,BEDS_PER_BATH,TOTAL_BEDS_BATH
0,House for sale,94601238.0,5,5,5938.49,"Moratuwa, Colombo",Colombo,Moratuwa,15930.183936,Very Large,1.00,10
1,House for sale,46044725.0,3,3,1768.45,"Homagama, Colombo",Colombo,Homagama,26036.769487,Medium,1.00,6
2,House for sale,90985626.0,5,4,5063.38,"Boralesgamuwa, Colombo",Colombo,Boralesgamuwa,17969.345773,Very Large,1.25,9
3,House for sale,28967644.0,3,2,2619.82,"Piliyandala, Colombo",Colombo,Piliyandala,11057.112321,Large,1.50,5
4,Villa for sale,98596073.0,5,5,4914.25,"Boralesgamuwa, Colombo",Colombo,Boralesgamuwa,20063.300198,Very Large,1.00,10

In [111]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline

In [112]:
categorical_features = [
    "TYPE",
    "STATE",
    "LOCALITY"
]

numerical_features = [
    "BEDS",
    "BATH",
    "PROPERTYSQFT"
]

In [113]:
# pipeline

categorical_transformer = Pipeline(
    steps=[
        (
            "imputer",
            SimpleImputer(strategy="most_frequent")
        ),
        (
            "onehot",
            OneHotEncoder(
                handle_unknown="ignore",
                min_frequency=5
            )
        )
    ]
)

In [114]:
# ML Ready dataset save

df_fe.to_csv(
    "../dataset/processed/feature_engineered_house_prices.csv",
    index=False
)

print("Feature engineered dataset saved.")

Feature engineered dataset saved.