In [9]:
import pandas as pd
import numpy as np

In [10]:
df = pd.read_csv('../dataset/processed/cleaned_house_prices.csv')
df.head()

,TYPE,PRICE,BEDS,BATH,PROPERTYSQFT,ADDRESS,LOCALITY,FORMATTED_ADDRESS
0,House for sale,94601238.0,5,5,5938.49,"Moratuwa, Colombo",Moratuwa,"Moratuwa, Colombo"
1,House for sale,46044725.0,3,3,1768.45,"Homagama, Colombo",Homagama,"Homagama, Colombo"
2,House for sale,90985626.0,5,4,5063.38,"Boralesgamuwa, Colombo",Boralesgamuwa,"Boralesgamuwa, Colombo"
3,House for sale,28967644.0,3,2,2619.82,"Piliyandala, Colombo",Piliyandala,"Piliyandala, Colombo"
4,Villa for sale,98596073.0,5,5,4914.25,"Boralesgamuwa, Colombo",Boralesgamuwa,"Boralesgamuwa, Colombo"

In [11]:
target = "PRICE"

In [12]:
columns_to_drop = [
    "STREET_NAME",
    "BROKERTITLE",
    "MAIN_ADDRESS",
    "FORMATTED_ADDRESS",
    "ADMINISTRATIVE_AREA_LEVEL_2"
]

df_fe = df.drop(
    columns=columns_to_drop,
    errors="ignore"
)

print(df_fe.columns)

Index(['TYPE', 'PRICE', 'BEDS', 'BATH', 'PROPERTYSQFT', 'ADDRESS', 'LOCALITY'], dtype='object')

In [13]:
df_fe.isnull().sum()

TYPE            0
PRICE           0
BEDS            0
BATH            0
PROPERTYSQFT    0
ADDRESS         0
LOCALITY        0
dtype: int64

In [14]:
categorical_features = [
    "TYPE",
    "LOCALITY",
    "ADDRESS",
]

numerical_features = [
    "PRICE",
    "PROPERTYSQFT",
    "BEDS",
    "BATH"
]

In [ ]:
# price per square foot
df_fe["PRICE_PER_SQFT"] = df_fe["PRICE"] / df_fe["PROPERTYSQFT"]

In [16]:
# value category

def size_category(sqft):

    if sqft < 1000:
        return "Small"

    elif sqft < 2000:
        return "Medium"

    elif sqft < 3500:
        return "Large"

    else:
        return "Very Large"


df_fe["SIZE_CATEGORY"] = (
    df_fe["PROPERTYSQFT"]
    .apply(size_category)
)

In [17]:
df_fe["SIZE_CATEGORY"].value_counts()

SIZE_CATEGORY
Very Large    1224
Large         1013
Medium         626
Small          134
Name: count, dtype: int64

In [18]:
df_fe.head()

,TYPE,PRICE,BEDS,BATH,PROPERTYSQFT,ADDRESS,LOCALITY,PRICE_PER_SQFT,SIZE_CATEGORY
0,House for sale,94601238.0,5,5,5938.49,"Moratuwa, Colombo",Moratuwa,15930.183936,Very Large
1,House for sale,46044725.0,3,3,1768.45,"Homagama, Colombo",Homagama,26036.769487,Medium
2,House for sale,90985626.0,5,4,5063.38,"Boralesgamuwa, Colombo",Boralesgamuwa,17969.345773,Very Large
3,House for sale,28967644.0,3,2,2619.82,"Piliyandala, Colombo",Piliyandala,11057.112321,Large
4,Villa for sale,98596073.0,5,5,4914.25,"Boralesgamuwa, Colombo",Boralesgamuwa,20063.300198,Very Large